spring.application.name=bytebank
# A URL do seu banco de dados local (vamos chamar o banco de 'bytebank')
spring.datasource.url=jdbc:postgresql://localhost:5432/bytebank
spring.datasource.username=postgres
spring.datasource.password=162014

# O Spring vai criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update

# Para vermos os comandos SQL no terminal (óptimo para estudar)
spring.jpa.show-sql=true=

api.security.token.secret=123456